language: node_js
node_js:
- node
- '6'
branches:
  except:
  - master
deploy:
- provider: script
  skip_cleanup: true
  script: ./scripts/githubPages.sh
  on:
    branch: develop
    node: '6'
- provider: s3
  access_key_id: $S3_ACCESS_KEY
  secret_access_key: $S3_SECRET_KEY
  bucket: "bervan-draft"
  skip_cleanup: true
  local_dir: dist
  region: eu-central-1
  on:
    branch: version2
    node: '6'
env:
  global:
    - secure: >-
            JjiBt47rI2Sy2cCNuDnT+9Hz/iJzn9DoL5WsDM/aBKj2C4vODV2wrCd3WNld6qtWjnv8iFGtwXEbwen8KDwNITct402fERCxyO6ZldapG1s840DH5fg6PSArJhfw4c2DuS7552JDh7dl+O1k6PifUujFZyWBesi7MtMuJAQ33fpx+aKnlRqDSShaNVxL265fFZFzTivooUmPRv9q7n2NrO9ZypmcIDv9rtdZsFdFMfxZWwkRjLsq6jt7L4FSi/+dnKTXwpqiRKFnVfQLabIe3hUCegGS01cWks+VUeyjVwaKKxsG9c7a4sY7JpQz2niOfZvNtYEqoFm/9I4IodBvg3Z7SpQIvOpiOU0A4IMyJq4oa3wkpe1cW5oHaikW2KEYDQ91Aa+/rR67gqL/lxFArfIGyaJhA8rU7AeNl9u2/2TPwYdrLX1uU7hZKQ4UEn4JAzLlE6TbQN4g1ITpYgYyn4vJH/PkxfipXT3BDTFj7zCYFV1DZ/xToggUG7F4MAYI5+T8CpuP5+AF7FPLdsORouAtawaqlKKy87tOF+kJyOEh6LBMzucakWN97suFiRcdjq8P7mOtaWVzJR5j+v/J3Qr7XvTI2xku8G6FAGOzXqQb8lOuV5idHoo+OyUVxxTYSrY0pIyMTcugeFRC46Plk6lSnUT5fwXIfpBOdgCxTEY=
    - GIT_DEPLOY_REPO=https://$GITHUB_TOKEN@github.com/easybird/bervandesign.be.git
