language: node_js
node_js:
- node
- '6'
branches:
  except:
  - master
deploy:
- provider: github-pages
  skip_cleanup: true
  script: ./scripts/githubPages.sh
  on:
    branch: develop
    node: '6'
- provider: s3
  access_key_id:
    secure: "oixbUORH1/FZU8kZhLOSBBJHk/WnpFDZWSWPifIe2vIz4bGeVj7v/JJMTuFWgWI7jJV8Gb11b9eyufRNQNA1LdAMWYtbTl1uJriI3qxdcYLQWjuO7UqzZYxl3Vz/pT7eiRPV33zp5gntX4eWoqCbczGZtcF0OqTj5n6IUjWLv00BK3agKz3LQhahG6WXpIHWcyPvYPDbp/KtmKiev36lxSry8elGi8+THa8DbkDcA27j423QOoJzFDdf/qxj5XIiaGAWeAOjIv6w/WzJj9hFdip46O4mb8YqPlRIG7wGn9ioaT39jgLf/+vbE/XG3TE9QFE0mkKpRhCVINL23lg+nsIXrowFQLeskE6LGj0QJgBF18EYhhSLkirp2cTlRfManAspO+78T8WvpffzZCgRhejICKdCi710oxLwF8jkUusexrjWhoncjL9u3IYzHADT+GqcKZtqVMGLhE3nxfL0SV3t8JngMgvzszb4JCdSmnljepAzXfmtdx0yHBCv7zhTmEyqLtlslq0PPeAJWx4RFZ4w0gL1c0z6ZRgx7on4jfUnkVk3KNz3bYHDkV/XJb0B+etK5WRfLcFPDLS/ZVY09OfzOWtZsgb6BTzGuvuhqBe6aC7ud6wm3PF1cOmyRjarC1f+MUKneHMI+PoxCbmC1C3W2t+7DDyEIZVgqZIe2DY="
  secret_access_key:
    secure: "RIgrHmyDNAKp7nlu0GwVQBl0WmJAAYlP1QXKh0y3Yo4DGaSceAtN5qTx9bnhCmQasKAGei803p7AqShTDFuuCx0buAiLAtzB4XuQZcnoiQYr5Kykb2EFP0HAwVymPFxVAuhAm4Jm19nWCgydIuejWTnpPpWKXGy0JVRCjS02excGayj2VXdr2GvgkxXZm7dOQ2ftVvTNb+PCAR4AapZgWHpg8i7ZHIBp+KX+qbAMtp4UOW6cnW3nTC7nNWFKNahtjx7SzdEyz1nE1VJQrm2tSiJ2lGxUdrQZsMrooD44bBXUXx8tR5jqMTTRqOb1FH9kivqLbs52bOXdPBr24Ca9uFJaaNF/3SiyVVY7Q9XoeCI7a9Sn3zGFRs0uNusTxr0LmcnyiwRMJDBowTU9o+qSVha/NffFCNHf7nYl0FwytR60gq2nrtXXpfYJM4oSMEk2e0UkpGFPhE2oHJ/eS0UIpLqkdE/M0L0eQ2/i26tFHeFp4SSoibK0DCMpxfQdKn5o4HY14oqghcC3OM2vS+aatazF/n+vEg8YRoOmuyfFRUg2MMHbf1W3aTHZRy8ap5HxG5xOmxA8r7gBiX3iXwq9LpH+Sv2hawAcgHnqJN0Apz1liMrXdewSjC4K8gSSD5Z2PrWclAqnMVjHoY64nUBcd8SddlqaB60KvZG91kXb/H8="
  bucket: "bervan-draft"
  skip_cleanup: true
  local_dir: dist
  region: Frankfurt
  on:
    branch: version2
    node: '6'
env:
  global:
    - secure: >-
            JjiBt47rI2Sy2cCNuDnT+9Hz/iJzn9DoL5WsDM/aBKj2C4vODV2wrCd3WNld6qtWjnv8iFGtwXEbwen8KDwNITct402fERCxyO6ZldapG1s840DH5fg6PSArJhfw4c2DuS7552JDh7dl+O1k6PifUujFZyWBesi7MtMuJAQ33fpx+aKnlRqDSShaNVxL265fFZFzTivooUmPRv9q7n2NrO9ZypmcIDv9rtdZsFdFMfxZWwkRjLsq6jt7L4FSi/+dnKTXwpqiRKFnVfQLabIe3hUCegGS01cWks+VUeyjVwaKKxsG9c7a4sY7JpQz2niOfZvNtYEqoFm/9I4IodBvg3Z7SpQIvOpiOU0A4IMyJq4oa3wkpe1cW5oHaikW2KEYDQ91Aa+/rR67gqL/lxFArfIGyaJhA8rU7AeNl9u2/2TPwYdrLX1uU7hZKQ4UEn4JAzLlE6TbQN4g1ITpYgYyn4vJH/PkxfipXT3BDTFj7zCYFV1DZ/xToggUG7F4MAYI5+T8CpuP5+AF7FPLdsORouAtawaqlKKy87tOF+kJyOEh6LBMzucakWN97suFiRcdjq8P7mOtaWVzJR5j+v/J3Qr7XvTI2xku8G6FAGOzXqQb8lOuV5idHoo+OyUVxxTYSrY0pIyMTcugeFRC46Plk6lSnUT5fwXIfpBOdgCxTEY=
    - GIT_DEPLOY_REPO=https://$GITHUB_TOKEN@github.com/easybird/bervandesign.be.git
